apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: core-backend
spec:
  replicas: {{ .Values.replicas | default 1 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "common.labels.selectorLabels" . | nindent 6 }}
  strategy:
    # TODO: update this based on replicas/auto scaling.
    # We should be able to infer some reasonable defaults also for redis, etc
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "common.labels.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        # TODO: add init container that can bootstrap the DB if necessary (for
        # demo, single node, etc)
        - name: {{ include "common.names.name" . }}
          image: {{ include "common.images.image" (dict "local" .Values.image "global" $) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: plextracenvsecrets
          {{- with .Values.volumes }}
          volumeMounts:
          {{- range $volume := . }}
          - mountPath: {{ .mountPath }}
            name: {{ .name }}
          {{- end }}
          {{- end }}

          ports:
            - name: api
              containerPort: 4350
              protocol: TCP

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path:  /api/v2/health/live
              port: 4350
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path:  /api/v2/health/full
              port: 4350
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end -}}

      
      {{- with .Values.volumes }}
      volumes:
      {{- range $volume := . }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ $.Chart.Name }}-{{ .name }}
      {{- end }}
      {{- end }}

      restartPolicy: Always

