apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "common.labels.selectorLabels" . | nindent 6 }}
  strategy:
    {{- if gt (.Values.replicas | default 1 | int) 1 }}
    type: RollingUpdate
    {{- else }}
    type: Recreate
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      containers:
        # TODO: add init container that can bootstrap the DB if necessary (for
        # demo, single node, etc)
      - name: {{ include "common.names.name" . }}
        image: {{ include "common.images.image" (dict "local" .Values.image "global" $) }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.command }}
        command:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: RUNAS_APPUSER
          value: "true"
        {{- with .Values.sentryDSN }}
        - name: SENTRY_DSN_BACKEND
          value: {{ . | quote}}
        {{- end }}
        - name: CB_API_USER
          {{- include "common.secret.fromValueOrSecret" (
                dict
                "key" "couchbaseUsername"
                "secret" (default "couchbase-secret" .Values.couchbaseExistingSecret)
                "secretKey" (printf "%s%s" (default "" .Values.couchbaseExistingSecretKeyPrefix) "username")
                "rootContext" . 
          ) | nindent 10 }}
        - name: CB_API_PASS
          {{- include "common.secret.fromValueOrSecret" (
                dict
                "key" "couchbasePassword"
                "secret" (default "couchbase-secret" .Values.couchbaseExistingSecret)
                "secretKey" (printf "%s%s" (default "" .Values.couchbaseExistingSecretKeyPrefix) "password")
                "rootContext" . 
          ) | nindent 10 }}
        - name: CB_ADMIN_USER
          {{- include "common.secret.fromValueOrSecret" (
                dict
                "key" "couchbaseAdminUsername"
                "secret" (default "couchbase-admin-secret" .Values.couchbaseExistingSecret)
                "secretKey" "CB_ADMIN_USER"
                "rootContext" . 
          ) | nindent 10 }}
        - name: CB_ADMIN_PASS
          {{- include "common.secret.fromValueOrSecret" (
                dict
                "key" "couchbaseAdminPassword"
                "secret" (default "couchbase-admin-secret" .Values.couchbaseExistingSecret)
                "secretKey" "CB_ADMIN_PASS"
                "rootContext" . 
          ) | nindent 10 }}
        - name: COUCHBASE_URL
          value: {{ include "common.names.dependencyName" (merge (dict "dependency" "couchbase") .) }}
        envFrom:
        - secretRef:
            name: {{ include "common.names.name" . }}-secret
        - configMapRef:
            name: {{ include "common.names.name" . }}-configmap
        {{- with .Values.volumes }}
        volumeMounts:
        {{- range $name, $spec := . }}
        - mountPath: {{ $spec.mountPath }}
          name: {{ $name }}
        {{- end }}
        {{- end }}

        ports:
        - name: api
          containerPort: 4350
          protocol: TCP

        resources:
          {{- toYaml .Values.resources | nindent 10 }}

        livenessProbe:
          httpGet:
            path:  /api/v2/health/live
            port: 4350
          initialDelaySeconds: 10
          timeoutSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path:  /api/v2/health/full
            port: 4350
          initialDelaySeconds: 10
          timeoutSeconds: 10
          failureThreshold: 6

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end -}}

      
      {{- with .Values.volumes }}
      volumes:
        {{- range $name, $spec := . }}
      - name: {{ $name }}
        persistentVolumeClaim:
          claimName: {{ $.Chart.Name }}-{{ $name }}
      {{- end }}
      {{- end }}

      restartPolicy: Always

