---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.name" . }}
  labels:
    {{- include "common.labels" .  | nindent 4 }}
    app.kubernetes.io/component: "core-backend"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 4350
    protocol: TCP
    name: http-plextracapi
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
