apiVersion: v1
data:
  customer_curated.rules: |
    ## Custom WAF Rules Below
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/version: 2.23.4
  name: customer-curated-waf-rules
  namespace: {{ include "plextrac.namespace" . }}
