apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: orchestrator
    app.kubernetes.io/instance: event-orchestrator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: event-orchestrator
    app.kubernetes.io/part-of: plextrac
    name: event-orchestrator
  name: event-orchestrator
  namespace: {{ include "plextrac.namespace" . }}
spec:
  replicas: {{ .Values.replicaCounts.eventOrchestrator }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: event-orchestrator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        prometheus.io/scrape: "true"
      labels:
        app: event-orchestrator
        app.kubernetes.io/component: orchestrator
        app.kubernetes.io/instance: event-orchestrator
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: event-orchestrator
        app.kubernetes.io/part-of: plextrac
    spec:
      {{- include "plextrac.imagePullSecrets" . | nindent 6 }}
      {{- include "plextrac.podSecurityContext" . | nindent 6 }}
      containers:
      - args:
        - run
        - start:event-orchestrator
        command:
        - npm
        env:
        - name: CB_API_PASS
          valueFrom:
            secretKeyRef:
              key: CB_API_PASS
              name: application-secrets
        - name: CB_API_USER
          valueFrom:
            secretKeyRef:
              key: CB_API_USER
              name: application-secrets
        - name: CORE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: CORE_API_BASE_URL
              name: env-config
        - name: INTERNAL_API_KEY_SHARED
          valueFrom:
            secretKeyRef:
              key: INTERNAL_API_KEY_SHARED
              name: application-secrets
        - name: LAUNCH_DARKLY_SDK_KEY
          valueFrom:
            secretKeyRef:
              key: LAUNCH_DARKLY_SDK_KEY
              name: shared-secrets
        - name: LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              key: LOG_FORMAT
              name: env-config
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: env-config
        - name: LOG_SERVICE_NAME
          value: event-orchestrator
        - name: PG_CKEDITOR_DB
          valueFrom:
            secretKeyRef:
              key: PG_CKEDITOR_DB
              name: application-secrets
        - name: PG_CKEDITOR_RO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PG_CKEDITOR_RO_PASSWORD
              name: application-secrets
        - name: PG_CKEDITOR_RO_USER
          valueFrom:
            secretKeyRef:
              key: PG_CKEDITOR_RO_USER
              name: application-secrets
        - name: PG_CORE_DB
          valueFrom:
            secretKeyRef:
              key: PG_CORE_DB
              name: application-secrets
        - name: PG_CORE_RO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RO_PASSWORD
              name: application-secrets
        - name: PG_CORE_RO_USER
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RO_USER
              name: application-secrets
        - name: PG_CORE_RW_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RW_PASSWORD
              name: application-secrets
        - name: PG_CORE_RW_USER
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RW_USER
              name: application-secrets
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: application-secrets
        envFrom:
        - configMapRef:
            name: env-config
        image: {{ include "plextrac.image" (dict "image" .Values.images.backend "root" $) }}
        imagePullPolicy: Always
        name: event-orchestrator
        ports:
        - containerPort: 4354
          name: event-orch-port
        resources:
          {{- toYaml .Values.resources.eventOrchestrator | nindent 10 }}
        volumeMounts:
        - mountPath: /usr/src/plextrac-api/uploads
          name: plextracapi-vol
      restartPolicy: Always
      volumes:
      - name: plextracapi-vol
        persistentVolumeClaim:
          claimName: plextracapi-pvc
