apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: ai
    app.kubernetes.io/instance: ruxpin
    app.kubernetes.io/managed-by: ArgoCD
    app.kubernetes.io/name: ruxpin
    app.kubernetes.io/part-of: plextrac
    app.kubernetes.io/version: 2.23.4
    name: ruxpin
  name: ruxpin
  namespace: {{ include "plextrac.namespace" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ruxpin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        prometheus.io/scrape: "true"
      labels:
        app: ruxpin
        app.kubernetes.io/component: ai
        app.kubernetes.io/instance: ruxpin
        app.kubernetes.io/managed-by: ArgoCD
        app.kubernetes.io/name: ruxpin
        app.kubernetes.io/part-of: plextrac
        app.kubernetes.io/version: 2.23.4
    spec:
      containers:
      - env:
        - name: AI_ENDPOINT_ID
          valueFrom:
            configMapKeyRef:
              key: AI_ENDPOINT_ID
              name: env-config
        - name: AI_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: AI_PROJECT_ID
              name: env-config
        - name: DEV
          value: "False"
        - name: DEBUG_METRICS
          value: "False"
        - name: GCP_PROJECT
          valueFrom:
            configMapKeyRef:
              key: GCP_PROJECT
              name: env-config
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/gcp/ruxpin-svc-acct-creds.json
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              key: JWT_KEY
              name: application-secrets
        - name: LAUNCH_DARKLY_SDK_KEY
          valueFrom:
            secretKeyRef:
              key: LAUNCH_DARKLY_SDK_KEY
              name: shared-secrets
        - name: PG_CORE_AI_SQL_USER
          valueFrom:
            secretKeyRef:
              key: PG_CORE_AI_SQL_USER
              name: application-secrets
        - name: PG_CORE_AI_SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PG_CORE_AI_SQL_PASSWORD
              name: application-secrets
        - name: PG_CORE_DB
          valueFrom:
            secretKeyRef:
              key: PG_CORE_DB
              name: application-secrets
        - name: PG_CORE_RO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RO_PASSWORD
              name: application-secrets
        - name: PG_CORE_RO_USER
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RO_USER
              name: application-secrets
        - name: PG_CORE_RW_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RW_PASSWORD
              name: application-secrets
        - name: PG_CORE_RW_USER
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RW_USER
              name: application-secrets
        - name: PG_HOST
          valueFrom:
            configMapKeyRef:
              key: PG_HOST
              name: env-config
        - name: PLEXAI_ANSWER_ENDPOINT_ID
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_ANSWER_ENDPOINT_ID
              name: env-config
        - name: PLEXAI_ANSWER_REGION
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_ANSWER_REGION
              name: env-config
        - name: PLEXAI_ASKAI_GEMINI_API_MODEL_NAME
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_ASKAI_GEMINI_API_MODEL_NAME
              name: env-config
        - name: PLEXAI_ASKAI_EMBEDDING_ENDPOINT_ID
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_ASKAI_EMBEDDING_ENDPOINT_ID
              name: env-config
        - name: PLEXAI_ASKAI_EMBEDDING_REGION
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_ASKAI_EMBEDDING_REGION
              name: env-config
        - name: PLEXAI_ASKAI_GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              key: PLEXAI_ASKAI_GEMINI_API_KEY
              name: shared-secrets
        - name: PLEXAI_DATASET_ID_VECTOR
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_DATASET_ID_VECTOR
              name: env-config
        - name: PLEXAI_EMBEDDING_ENDPOINT_ID
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_EMBEDDING_ENDPOINT_ID
              name: env-config
        - name: PLEXAI_EMBEDDING_REGION
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_EMBEDDING_REGION
              name: env-config
        - name: PLEXAI_ENDPOINT_ID
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_ENDPOINT_ID
              name: env-config
        - name: PLEXAI_GCP_PROJECT
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_GCP_PROJECT
              name: env-config
        - name: PLEXAI_GCP_REGION
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_GCP_REGION
              name: env-config
        - name: PLEXAI_GCP_WAREHOUSE_PROJECT
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_GCP_WAREHOUSE_PROJECT
              name: env-config
        - name: PLEXAI_GCP_WAREHOUSE_REGION
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_GCP_WAREHOUSE_REGION
              name: env-config
        - name: PLEXAI_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_PROJECT_ID
              name: env-config
        - name: PLEXAI_SUMMARIZATION_ENDPOINT_ID
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_SUMMARIZATION_ENDPOINT_ID
              name: env-config
        - name: PLEXAI_SUMMARIZATION_REGION
          valueFrom:
            configMapKeyRef:
              key: PLEXAI_SUMMARIZATION_REGION
              name: env-config
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: application-secrets
        image: {{ .Values.images.ruxpin.repository }}:{{ .Values.images.ruxpin.tag }}
        imagePullPolicy: Always
        name: ruxpin
        ports:
        - containerPort: 5000
          name: ruxpin-port
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 20m
            memory: 256Mi
        volumeMounts:
        - mountPath: /usr/src/app/cve_by_year
          name: ruxpin-cve-vol
        - mountPath: /var/secrets/gcp
          name: plexai-creds-json-volume
          readOnly: true
      imagePullSecrets:
      - name: regcred-dorf
      initContainers:
      - args:
        - -c
        - |
          gcloud auth activate-service-account --key-file=/var/secrets/gcp/ruxpin-svc-acct-creds.json
        command:
        - /bin/sh
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/gcp/ruxpin-svc-acct-creds.json
        - name: CLOUDSDK_CONFIG
          value: /tmp/gcloud
        image: google/cloud-sdk:530.0.0-alpine
        name: perform-gcloud-auth
        volumeMounts:
        - mountPath: /var/secrets/gcp
          name: plexai-creds-json-volume
          readOnly: true
      securityContext:
        fsGroup: 1337
        runAsGroup: 1337
        runAsUser: 1337
      volumes:
      - hostPath:
          path: /opt/plextrac/cve_by_year
          type: Directory
        name: ruxpin-cve-vol
      - name: plexai-creds-json-volume
        secret:
          defaultMode: 420
          items:
          - key: ruxpin-svc-acct-creds.json
            path: ruxpin-svc-acct-creds.json
          secretName: shared-secrets
