apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: integration-worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/instance: integration-worker
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: integration-worker
    app.kubernetes.io/part-of: plextrac
    name: integration-worker
    serviceName: integration-worker
  name: integration-worker
  namespace: {{ include "plextrac.namespace" . }}
spec:
  replicas: {{ .Values.replicaCounts.integrationWorker }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: integration-worker
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        prometheus.io/scrape: "true"
      labels:
        app: integration-worker
        app.kubernetes.io/component: worker
        app.kubernetes.io/instance: integration-worker
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: integration-worker
        app.kubernetes.io/part-of: plextrac
        name: integration-worker
        serviceName: integration-worker
    spec:
      {{- include "plextrac.imagePullSecrets" . | nindent 6 }}
      containers:
      - args:
        - run
        - start:integration-worker
        command:
        - npm
        env:
        - name: CB_API_PASS
          valueFrom:
            secretKeyRef:
              key: CB_API_PASS
              name: application-secrets
        - name: CB_API_USER
          valueFrom:
            secretKeyRef:
              key: CB_API_USER
              name: application-secrets
        - name: PG_CORE_DB
          valueFrom:
            secretKeyRef:
              key: PG_CORE_DB
              name: application-secrets
        - name: PG_CORE_RO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RO_PASSWORD
              name: application-secrets
        - name: PG_CORE_RO_USER
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RO_USER
              name: application-secrets
        - name: PG_CORE_RW_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RW_PASSWORD
              name: application-secrets
        - name: PG_CORE_RW_USER
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RW_USER
              name: application-secrets
        - name: LAUNCH_DARKLY_SDK_KEY
          valueFrom:
            secretKeyRef:
              key: LAUNCH_DARKLY_SDK_KEY
              name: shared-secrets
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: application-secrets
        - name: SENTRY_DSN_BACKEND
          valueFrom:
            secretKeyRef:
              key: SENTRY_DSN_BACKEND
              name: shared-secrets
        - name: CLOUD_STORAGE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: CLOUD_STORAGE_ENDPOINT
              name: env-config
        - name: CLOUD_STORAGE_SSL
          valueFrom:
            configMapKeyRef:
              key: CLOUD_STORAGE_SSL
              name: env-config
        - name: CLOUD_STORAGE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: CLOUD_STORAGE_ACCESS_KEY
              name: application-secrets
        - name: CLOUD_STORAGE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: CLOUD_STORAGE_SECRET_KEY
              name: application-secrets
        - name: NODE_OPTIONS
          value: --max-old-space-size=2800
        envFrom:
        - configMapRef:
            name: env-config
        image: {{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /health
            port: 9100
          initialDelaySeconds: 30
          timeoutSeconds: 10
        name: integration-worker
        ports:
        - containerPort: 9100
          name: int-worker-port
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /health
            port: 9100
          initialDelaySeconds: 30
          timeoutSeconds: 10
        resources:
          {{- toYaml .Values.resources.integrationWorker | nindent 10 }}
        volumeMounts:
        - mountPath: /usr/src/plextrac-api/uploads
          name: plextracapi-vol
      restartPolicy: Always
      volumes:
      - name: plextracapi-vol
        persistentVolumeClaim:
          claimName: plextracapi-pvc
