apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: platform-metrics-exporter
    app.kubernetes.io/instance: platform-metrics-exporter
    app.kubernetes.io/managed-by: ArgoCD
    app.kubernetes.io/name: platform-metrics-exporter
    app.kubernetes.io/part-of: plextrac
    app.kubernetes.io/version: 2.23.4
    name: platform-metrics-exporter
  name: platform-metrics-exporter
  namespace: {{ include "plextrac.namespace" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: platform-metrics-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        prometheus.io/scrape: "true"
      labels:
        app: platform-metrics-exporter
        app.kubernetes.io/component: platform-metrics-exporter
        app.kubernetes.io/instance: platform-metrics-exporter
        app.kubernetes.io/managed-by: ArgoCD
        app.kubernetes.io/name: platform-metrics-exporter
        app.kubernetes.io/part-of: plextrac
        app.kubernetes.io/version: 2.23.4
        name: platform-metrics-exporter
    spec:
      containers:
      - args:
        - run
        - start:platform-metrics-exporter
        command:
        - npm
        env:
        - name: LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              key: LOG_FORMAT
              name: env-config
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: env-config
        - name: LOG_SERVICE_NAME
          value: platform-metrics-exporter
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: application-secrets
        - name: PG_CORE_DB
          valueFrom:
            secretKeyRef:
              key: PG_CORE_DB
              name: application-secrets
        - name: PG_CORE_RO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RO_PASSWORD
              name: application-secrets
        - name: PG_CORE_RO_USER
          valueFrom:
            secretKeyRef:
              key: PG_CORE_RO_USER
              name: application-secrets
        envFrom:
        - configMapRef:
            name: env-config
        image: {{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}
        imagePullPolicy: Always
        name: platform-metrics-exporter
        ports:
        - containerPort: 4357
          name: plt-met-port
        resources:
          limits:
            cpu: 1150m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
      imagePullSecrets:
      - name: regcred-dorf
      restartPolicy: Always
