{{- if and (eq .Values.secrets.mode "externalSecrets") .Values.secrets.externalSecrets.tls.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/version: 2.23.4
  name: plextrac-tls
  namespace: {{ include "plextrac.namespace" . }}
spec:
  data:
  - remoteRef:
      key: {{ .Values.secrets.externalSecrets.tls.remoteKey }}
    secretKey: plextrac
  refreshInterval: {{ .Values.secrets.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.secrets.externalSecrets.secretStoreRef.kind }}
    name: {{ .Values.secrets.externalSecrets.secretStoreRef.name }}
  target:
    name: {{ .Values.secrets.externalSecrets.tls.targetSecretName }}
    template:
      data:
        tls.crt: '{{ "{{ .plextrac | pkcs12cert }}" }}'
        tls.key: '{{ "{{ .plextrac | pkcs12key }}" }}'
      type: kubernetes.io/tls

{{- end }}
