{{- if eq .Values.secrets.mode "externalSecrets" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/version: 2.23.4
  name: {{ .Values.secrets.externalSecrets.shared.targetSecretName }}-es
spec:
  dataFrom:
  - extract:
      key: {{ .Values.secrets.externalSecrets.shared.remoteKey }}
  refreshInterval: {{ .Values.secrets.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.secrets.externalSecrets.secretStoreRef.kind }}
    name: {{ .Values.secrets.externalSecrets.secretStoreRef.name }}
  target:
    creationPolicy: Owner
    name: {{ .Values.secrets.externalSecrets.shared.targetSecretName }}

{{- end }}
