apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers Content-Security-Policy "default-src 'self';";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      send_timeout 6000;
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "6000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "6000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "6000"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app.kubernetes.io/version: 2.23.4
  name: plextracapi-ingress
  namespace: {{ include "plextrac.namespace" . }}
spec:
  ingressClassName: nginx
  rules:
  - host: k3s-instance.plextrac.com
    http:
      paths:
      - backend:
          service:
            name: plextracapi
            port:
              number: 4350
        path: /api/
        pathType: ImplementationSpecific
