apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3000"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app.kubernetes.io/version: 2.23.4
  name: ruxpin-ingress
  namespace: {{ include "plextrac.namespace" . }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ include "plextrac.ingressHost" . }}
    http:
      paths:
      - backend:
          service:
            name: ruxpin
            port:
              number: 5000
        path: /api/plexai(/|$)(.*)
        pathType: ImplementationSpecific
