apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  labels:
    app.kubernetes.io/version: 2.23.4
  name: redis-pvc
  namespace: {{ include "plextrac.namespace" . }}
spec:
  {{- include "plextrac.pvcSpec" (dict "claim" "redis" "size" "1Gi" "root" $) | nindent 2 }}
