apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/version: 2.23.4
    serviceName: couchbase
  name: plextracdb
  namespace: {{ include "plextrac.namespace" . }}
spec:
  ports:
  - name: rest-port
    port: 8091
    targetPort: rest-port
  - name: capi-port
    port: 8092
    targetPort: capi-port
  - name: query-port
    port: 8093
    targetPort: query-port
  - name: fts-http-port
    port: 8094
    targetPort: fts-http-port
  - name: memcached-port
    port: 11210
    targetPort: memcached-port
  selector:
    app: plextracdb
