apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/version: 2.23.4
    serviceName: ckeditor
  name: ckeditor
  namespace: {{ include "plextrac.namespace" . }}
spec:
  ports:
  - name: ckeditor-port
    port: 8000
    targetPort: ckeditor-port
  selector:
    app: ckeditor-backend
