apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: ArgoCD
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: plextrac
    app.kubernetes.io/version: 2.23.4
    name: redis
    serviceName: redis
  name: redis
  namespace: {{ include "plextrac.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  template:
    metadata:
      annotations:
        prometheus.io/metricsPortNumber: "9121"
        prometheus.io/scrape: "true"
      labels:
        app: redis
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: redis
        app.kubernetes.io/managed-by: ArgoCD
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: plextrac
        app.kubernetes.io/version: 2.23.4
        name: redis
        serviceName: redis
    spec:
      containers:
      - env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: application-secrets
        image: {{ .Values.images.redisExporter.repository }}:{{ .Values.images.redisExporter.tag }}
        name: redis-exporter
        ports:
        - containerPort: 9121
          name: redis-exporter
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 59000
          runAsUser: 59000
      - args:
        - --requirepass
        - $(REDIS_PASSWORD)
        - --maxmemory
        - 2gb
        - --loglevel
        - warning
        command:
        - redis-server
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: application-secrets
        image: {{ .Values.images.redis.repository }}:{{ .Values.images.redis.tag }}
        name: redis
        ports:
        - containerPort: 6379
          name: redis-port
        resources:
          limits:
            cpu: 800m
            memory: 2Gi
          requests:
            cpu: 30m
            memory: 256Mi
        volumeMounts:
        - mountPath: /data
          name: redis-data
      restartPolicy: Always
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
