{{- if .Values.createRedisSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.name" . }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ pluck "password" .Values.global.redis .Values | first | default (randAlphaNum 32) | b64enc }}
{{- end }}
