global:
  namespace: plextrac
  createNamespace: false
  ingress:
    host: plextrac.example.com
    tlsSecretName: plextrac-com-tls
    certManagerClusterIssuer: ""

secrets:
  mode: manual
  manual:
    createKubernetesSecrets: true
    generatedSecrets:
      application:
        name: application-secrets
        stringData:
          # Optional override. Can be blank.
          ADMIN_EMAIL: ""
      shared:
        name: shared-secrets
        stringData:
          # Required for CKEditor. Enter your license key.
          CKEDITOR_SERVER_LICENSE_KEY: ""
      registryCredentials:
        enabled: false   # Set to true and provide dockerconfigjson to pull from a private registry.
        name: regcred-dorf
        # Generate the blob with:
        #   kubectl create secret docker-registry tmp \
        #     --docker-server=<registry> --docker-username=<user> --docker-password=<pass> \
        #     --dry-run=client -o json | jq -r '.data[".dockerconfigjson"]' | base64 -d
        dockerconfigjson: ""
      tls:
        enabled: false
        name: plextrac-com-tls
        crt: ""
        key: ""
      additional:
        - name: event-orchestrator-secrets
          type: Opaque
          stringData:
            EVENT_ORCHESTRATOR_API_KEY: ""
