apiVersion: v2
name: plextrac
description: Deploys the PlexTrac application & any required dependencies
home: https://github.com/PlexTrac/helm-charts
icon: https://plextrac.com/wp-content/uploads/2021/10/cropped-PlexTrac-Symbol-Small-Use-192x192.png

type: application

# Represents the chart revision
version: 0.3.4

# Uses the "stable" tag for PlexTrac images
appVersion: "stable"

dependencies:
- name: common
  version: "~0.1"
  repository: "file://../common"
- name: couchbase
  condition: couchbase.enabled
  version: "~0.1"
  repository: "file://../couchbase"
- name: redis
  version: "~0.1"
  repository: "file://../redis"
  condition: redis.enabled
