global:
  ingressClassName: ""
  imageRegistry: ""
  imagePullSecrets: []
  registryCredentials: []
  storageClass: ""

  extraLabels: {}

  redis:
    # -- Specify redis password for main & sub-chart
    # overrides
    password: ""


# -- List of secrets that can be used to pull containers from private registries
# Reference https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials
# This must exist!
imagePullSecrets: []
# - name: regcred

registryCredentials: []

service:
  type: ClusterIP
  port: 8080

# -- Ingress configuration for the core-backend deployment
# This should only route requests to /api/
ingress:
  # -- Enable Ingress creation
  enabled: false
  # -- Configure the Ingress className
  className: ""
  # -- Configure Ingress annotations, eg for external-dns, cert-manager, etc
  annotations: {}
  # -- Define the host used in the Ingress
  host: plextrac.local


core-backend:
  extraLabels:
    app.kubernetes.io/component: "core-backend"

  image:
    repository: plextrac/plextracapi
    pullPolicy: Always
    tag: ""

  service:
    type: ClusterIP
    port: 4350

  resources:
    requests: {}
    limits: {}

  volumes:
    uploads:
      mountPath: /usr/src/plextrac-api/uploads
      storageClassName: ""
      storage: ""
      accessModes:
        - ReadWriteMany

  # -- Application specific secrets
  appSecrets:
  # MFA_KEY: ""
  # JWT_KEY: ""
  # COOKIE_KEY: ""
  # API_INTEGRATION_AUTH_CONFIG: ""
    PROVIDER_CODE_KEY: "foo"

  # -- Application specific environment variables
  appEnvVars:
    CB_BUCKET: reportMe
  # ADMIN_EMAIL: ""
  # OVERRIDE_...: ""

  # -- Enable Sentry reporting
  sentryDSN: ""

  # -- Override host for Couchbase connection
  couchbaseHost: ""
  # -- Override port for Couchbase connection
  couchbasePort: ""
  # -- Set username for connection to Couchbase
  # Mainly useful for an external Couchbase instance
  couchbaseUsername: ""
  # -- Set password for connection to Couchbase
  # Mainly useful for an external Couchbase instance
  couchbasePassword: ""
  # -- Use existing secret for couchbase credentials
  # If unset and no password is provided, default is `couchbase-secret`
  couchbaseExistingSecret: ""
  # -- Use prefix to extract username & password from existing secret 
  couchbaseExistingSecretKeyPrefix: ""

  
  externalRedisHost: ""
  externalRedisPort: ""

core-frontend: # This loads the PlexTrac UI locally vs from a CDN
  # This is technically not a sub-chart. The frontend is useless without the
  # backend (plextracapi) so this is just to keep things organized neatly.
  # As a bonus, we can eventually split this to a CDN (possibly Minio for local?)
  enabled: true
  replicas: 2
  extraLabels:
    app.kubernetes.io/component: "core-frontend"
  image:
    repository: plextrac/plextracnginx
    pullPolicy: Always
    tag: ""

  service:
    type: ClusterIP
    port: 8443  # the current container enforces HTTPS

# -- Configuration for the redis sub-chart
redis:
  # -- Enables the sub-chart
  enabled: true
  # -- Specify password for redis connection
  password: ""
  # -- Specify existing secret containing redis password
  existingSecret: ""
  # -- Specify lookup key for existing secret
  existingSecretPasswordKey: "redis-password"

# -- Configuration for the couchbase sub-chart
couchbase:
  enabled: true

  couchbaseUsername: cbhelmuser
  couchbasePassword: cbhelmpass

# -- Configuration for the postgres sub-chart
postgres:
  enabled: false
