apiVersion: v2
name: plextrac
description: PlexTrac self-hosted application chart for on-premises and private cloud deployments
home: https://github.com/PlexTrac/helm-charts
type: application
version: 2.28.0
appVersion: "2.27.1"
kubeVersion: ">=1.25.0-0"
keywords:
  - plextrac
  - security
  - saas
maintainers:
  - name: PlexTrac Platform
