{{- if .Values.createCouchbaseSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.name" . }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ pluck "couchbaseUsername" .Values.global .Values | first | default (randAlpha 16) | b64enc }}
  password: {{ pluck "couchbasePassword" .Values.global .Values | first | default (randAlphaNum 32) | b64enc }}
{{- end }}

{{- if .Values.createCouchbaseAdminSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.name" . }}-admin-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  CB_ADMIN_USER: {{ pluck "couchbaseAdminUsername" .Values.global .Values | first | default (randAlpha 16) | b64enc }}
  CB_ADMIN_PASS: {{ pluck "couchbaseAdminPassword" .Values.global .Values | first | default (randAlphaNum 32) | b64enc }}

{{- end }}