---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.name" . }}
  labels:
    {{- include "common.labels" .  | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: tcp-8091
    port: 8091
    protocol: TCP
    targetPort: 8091
  - name: tcp-8092
    port: 8092
    protocol: TCP
    targetPort: 8092
  - name: tcp-8093
    port: 8093
    protocol: TCP
    targetPort: 8093
  - name: tcp-8094
    port: 8094
    protocol: TCP
    targetPort: 8094
  - port: 11210
    protocol: TCP
    name: tcp-11210
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
